### ISSUE TITLE
[skip] also skips update of lastrevision?

### ISSUE THREAD

**Issue by brejoc** [dincamihai/obs-service-update_changelog#7]
Could it be that a `[skip]` also skips the update of `lastrevision`?

![Selection_023](https://user-images.githubusercontent.com/34246/74848017-38d3d400-5335-11ea-904a-f13554ededda.png)

I've pushed a change to openSUSE/salt and ran an `osc service disabledrun`. Everything was done correctly, but `lastrevision` was not updated.

**Comment by meaksh** [comment]
This is actually fixed by: https://github.com/openSUSE/obs-service-update_changelog/commit/2bd1e8f38034002ad5d1a573296a704c59799670

**Comment by brejoc** [comment]
Absolutely right. I was on an older release! Thx!
